name: Preview Deployment

on:
  pull_request:
    branches:
      - main
jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Deploy Preview
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: >
            pages deploy build
            --project-name ${{ secrets.DEV_ENVIRONMENT_PROJECT }}
            --branch preview-pr-${{ github.event.number }}
